workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages pub get
      - name: Build APK
        script: |
          cd mobile
          flutter build apk --release
    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Замените на ваш email
