import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

final getIt = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  // This would be generated by build_runner
  // Run: flutter pub run build_runner build
  
  // Manual registrations for now
  // getIt.registerSingleton<ApiClient>(ApiClient());
  // getIt.registerSingleton<BleService>(BleService());
  // getIt.registerFactory<AuthBloc>(() => AuthBloc(getIt()));
}
